name: deal
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2020.12.5
  - cairo=1.16.0
  - certifi=2020.12.5
  - cudatoolkit=10.1.243
  - dbus=1.13.6
  - expat=2.2.10
  - ffmpeg=4.3.1
  - fontconfig=2.13.1
  - freetype=2.10.4
  - gettext=0.19.8.1
  - glib=2.66.7
  - glib-tools=2.66.7
  - gmp=6.2.1
  - gnutls=3.6.13
  - graphite2=1.3.13
  - gst-plugins-base=1.14.5
  - gstreamer=1.18.3
  - harfbuzz=2.7.4
  - hdf5=1.10.6
  - icu=68.1
  - intel-openmp=2020.2
  - jasper=1.900.1
  - jpeg=9d
  - krb5=1.17.2
  - lame=3.100
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.75.0
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.66.7
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libnghttp2=1.43.0
  - libopencv=4.5.1
  - libpng=1.6.37
  - libpq=12.3
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=2.32.1
  - libwebp-base=1.2.0
  - libxcb=1.13
  - libxkbcommon=1.0.3
  - libxml2=2.9.10
  - lz4-c=1.9.3
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.3.0
  - mkl_random=1.1.1
  - mysql-common=8.0.22
  - mysql-libs=8.0.22
  - ncurses=6.2
  - nettle=3.6
  - ninja=1.10.2
  - nspr=4.29
  - nss=3.62
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - opencv=4.5.1
  - openh264=2.1.1
  - openssl=1.1.1j
  - pcre=8.44
  - pillow=8.1.2
  - pip=21.0.1
  - pixman=0.40.0
  - pthread-stubs=0.4
  - py-opencv=4.5.1
  - python=3.8.8
  - python_abi=3.8
  - pytorch=1.6.0
  - qt=5.12.9
  - readline=8.1
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.35.0
  - tk=8.6.10
  - torchvision=0.7.0
  - wheel=0.36.2
  - x264=1!161.3030
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.0
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - absl-py==0.12.0
    - cachetools==4.2.1
    - chardet==4.0.0
    - cycler==0.10.0
    - future==0.18.2
    - google-auth==1.27.1
    - google-auth-oauthlib==0.4.3
    - grpcio==1.36.1
    - h5py==3.2.1
    - idna==2.10
    - joblib==1.1.0
    - kiwisolver==1.3.1
    - kornia==0.4.1
    - markdown==3.3.4
    - matplotlib==3.3.4
    - oauthlib==3.1.0
    - protobuf==3.15.6
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pyparsing==2.4.7
    - python-dateutil==2.8.1
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scikit-learn==1.0.1
    - scipy==1.7.2
    - tensorboard==2.4.1
    - tensorboard-plugin-wit==1.8.0
    - threadpoolctl==3.0.0
    - tqdm==4.59.0
    - urllib3==1.26.4
    - werkzeug==1.0.1
